
package com.sg.vim.datamodel.service.vecc_sepa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSVinSoap", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSVinSoap {


    /**
     * <h3>登录中心服务接口，成功返回临时认证码32位KEY码，超时则需重新登录</h3><p>输入参数：Manufid = 企业编号(机构代码)，不能为空；Passwd =  报送密码；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param password
     * @param manufid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/loginW")
    @WebResult(name = "loginWResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "loginW", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LoginW")
    @ResponseWrapper(localName = "loginWResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LoginWResponse")
    public String loginW(
        @WebParam(name = "manufid", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String manufid,
        @WebParam(name = "password", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String password);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param ms
     * @param password
     * @param manufid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/loginB")
    @WebResult(name = "loginBResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "loginB", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LoginB")
    @ResponseWrapper(localName = "loginBResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LoginBResponse")
    public String loginB(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "manufid", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String manufid,
        @WebParam(name = "password", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String password);

    /**
     * <h3>查询已报送VIN数</h3><p>输入参数： key = 临时认证码，不能为空；xshzh =  型式核准号；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param xshzh
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/getVinCountByXshzh")
    @WebResult(name = "getVinCountByXshzhResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "getVinCountByXshzh", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetVinCountByXshzh")
    @ResponseWrapper(localName = "getVinCountByXshzhResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetVinCountByXshzhResponse")
    public String getVinCountByXshzh(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "xshzh", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String xshzh);

    /**
     * <h3>查询已报送VIN总数通过报送日期</h3><p>输入参数： key = 临时认证码，不能为空；dtFrom =  报送起始时间；dtTo =  报送截至时间；时间格式 YYYY-MM-DD HH24:MI:SS；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param dtTo
     * @param dtFrom
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/getVinCountByDate")
    @WebResult(name = "getVinCountByDateResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "getVinCountByDate", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetVinCountByDate")
    @ResponseWrapper(localName = "getVinCountByDateResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetVinCountByDateResponse")
    public String getVinCountByDate(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "dtFrom", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String dtFrom,
        @WebParam(name = "dtTo", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String dtTo);

    /**
     * <h3>删除已上报VIN信息</h3><p>输入参数： key = 临时认证码，不能为空；vin =  vin号；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param vin
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/delData")
    @WebResult(name = "delDataResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "delData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.DelData")
    @ResponseWrapper(localName = "delDataResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.DelDataResponse")
    public String delData(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "vin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String vin);

    /**
     * <h3>获取已报送形式核准号</h3><p>输入参数：key = 临时认证码，不能为空；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/getXshzh")
    @WebResult(name = "getXshzhResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "getXshzh", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetXshzh")
    @ResponseWrapper(localName = "getXshzhResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetXshzhResponse")
    public String getXshzh(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key);

    /**
     * <h3>退出本次连接</h3><p>输入参数；Passwd =  报送密码；key = 临时认证码，不能为空；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/logout")
    @WebResult(name = "logoutResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "logout", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LogoutResponse")
    public String logout(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param ms
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/logoutB")
    @WebResult(name = "logoutBResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "logoutB", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LogoutB")
    @ResponseWrapper(localName = "logoutBResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.LogoutBResponse")
    public String logoutB(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key);

    /**
     * <h3>密码修改</h3><p>输入参数：key = 临时认证码，不能为空；oldpasswd=旧密码；oldpasswd = 新密码；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param newpasswd
     * @param key
     * @param oldpasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/modifyPassword")
    @WebResult(name = "modifyPasswordResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "modifyPassword", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.ModifyPassword")
    @ResponseWrapper(localName = "modifyPasswordResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.ModifyPasswordResponse")
    public String modifyPassword(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "oldpasswd", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String oldpasswd,
        @WebParam(name = "newpasswd", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String newpasswd);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param ms
     * @param newpasswd
     * @param key
     * @param oldpasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/modifyPasswordB")
    @WebResult(name = "modifyPasswordBResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "modifyPasswordB", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.ModifyPasswordB")
    @ResponseWrapper(localName = "modifyPasswordBResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.ModifyPasswordBResponse")
    public String modifyPasswordB(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "oldpasswd", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String oldpasswd,
        @WebParam(name = "newpasswd", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String newpasswd);

    /**
     * <h3>获取某型式核准号的VIN详细列表(新接口，接收模式查看相关文档)</h3><p>输入参数；xshzh =  型式核准号；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param xshzh
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/getVinByXshzhNew")
    @WebResult(name = "getVinByXshzhNewResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "getVinByXshzhNew", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetVinByXshzhNew")
    @ResponseWrapper(localName = "getVinByXshzhNewResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetVinByXshzhNewResponse")
    public String getVinByXshzhNew(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "xshzh", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String xshzh);

    /**
     * <h3>获取某VIN的详细数据列表</h3><p>输入参数；vin =  VIN码；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param vin
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/getXshzhByVin")
    @WebResult(name = "getXshzhByVinResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "getXshzhByVin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetXshzhByVin")
    @ResponseWrapper(localName = "getXshzhByVinResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetXshzhByVinResponse")
    public String getXshzhByVin(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "vin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String vin);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param strVinData
     * @param ms
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "sendVinData_VinBS", action = "http://web1.vecc-sepa.org.cn/WSVin/sendVinData_VinBS")
    @WebResult(name = "sendVinData_VinBSResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "sendVinData_VinBS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.SendVinDataVinBS")
    @ResponseWrapper(localName = "sendVinData_VinBSResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.SendVinDataVinBSResponse")
    public String sendVinDataVinBS(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "strVinData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String strVinData);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param ms
     * @param strKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IsKey", action = "http://web1.vecc-sepa.org.cn/WSVin/IsKey")
    @WebResult(name = "IsKeyResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "IsKey", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.IsKey")
    @ResponseWrapper(localName = "IsKeyResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.IsKeyResponse")
    public String isKey(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "strKey", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String strKey);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param ms
     * @param manufid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/getPassword")
    @WebResult(name = "getPasswordResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "getPassword", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetPassword")
    @ResponseWrapper(localName = "getPasswordResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.GetPasswordResponse")
    public String getPassword(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "manufid", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String manufid);

    /**
     * <h3>上报Vin数据(新接口，接收模式查看相关文档)</h3><p>输入参数： key = 临时认证码，不能为空；vinData:  信息主体<br><br><br><br><p>
     * 
     * @param strVinData
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSVin/sendVinDataCFDJ")
    @WebResult(name = "sendVinDataCFDJResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "sendVinDataCFDJ", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.SendVinDataCFDJ")
    @ResponseWrapper(localName = "sendVinDataCFDJResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.SendVinDataCFDJResponse")
    public String sendVinDataCFDJ(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "strVinData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String strVinData);

    /**
     * <h3>内部调试</h3><br><br><br><br><p>
     * 
     * @param strVinData
     * @param ms
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "sendVinData_VinBS_CFDJ", action = "http://web1.vecc-sepa.org.cn/WSVin/sendVinData_VinBS_CFDJ")
    @WebResult(name = "sendVinData_VinBS_CFDJResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
    @RequestWrapper(localName = "sendVinData_VinBS_CFDJ", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.SendVinDataVinBSCFDJ")
    @ResponseWrapper(localName = "sendVinData_VinBS_CFDJResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", className = "cn.org.vecc_sepa.web1.wsvin.SendVinDataVinBSCFDJResponse")
    public String sendVinDataVinBSCFDJ(
        @WebParam(name = "MS", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String ms,
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String key,
        @WebParam(name = "strVinData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin")
        String strVinData);

}
