
package com.sg.vim.datamodel.service.fuellabel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FuelDataSysSTD", targetNamespace = "http://soap.catarc.info/", wsdlLocation = "http://soap.catarc.info/FuelDataSysSTD.asmx?wsdl")
public class FuelDataSysSTD
    extends Service
{

    private final static URL FUELDATASYSSTD_WSDL_LOCATION;
    private final static WebServiceException FUELDATASYSSTD_EXCEPTION;
    private final static QName FUELDATASYSSTD_QNAME = new QName("http://soap.catarc.info/", "FuelDataSysSTD");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://soap.catarc.info/FuelDataSysSTD.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUELDATASYSSTD_WSDL_LOCATION = url;
        FUELDATASYSSTD_EXCEPTION = e;
    }

    public FuelDataSysSTD() {
        super(__getWsdlLocation(), FUELDATASYSSTD_QNAME);
    }

    public FuelDataSysSTD(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUELDATASYSSTD_QNAME, features);
    }

    public FuelDataSysSTD(URL wsdlLocation) {
        super(wsdlLocation, FUELDATASYSSTD_QNAME);
    }

    public FuelDataSysSTD(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUELDATASYSSTD_QNAME, features);
    }

    public FuelDataSysSTD(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FuelDataSysSTD(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FuelDataSysSTDSoap
     */
    @WebEndpoint(name = "FuelDataSysSTDSoap")
    public FuelDataSysSTDSoap getFuelDataSysSTDSoap() {
        return super.getPort(new QName("http://soap.catarc.info/", "FuelDataSysSTDSoap"), FuelDataSysSTDSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FuelDataSysSTDSoap
     */
    @WebEndpoint(name = "FuelDataSysSTDSoap")
    public FuelDataSysSTDSoap getFuelDataSysSTDSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.catarc.info/", "FuelDataSysSTDSoap"), FuelDataSysSTDSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUELDATASYSSTD_EXCEPTION!= null) {
            throw FUELDATASYSSTD_EXCEPTION;
        }
        return FUELDATASYSSTD_WSDL_LOCATION;
    }

}
