
package com.sg.vim.service.vecc_sepa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <strong>Vin申报 Web 服务<a href="http://221.122.48.20/Vin/Drow.aspx?drowid=bssm" target="_blank"><font size="3" color="#FF0000">(详细使用说明点此下载)</font></a><br><br></strong>数据来源于<strong>中国环境保护部机动车排污监控中心</strong> <a href="http://www.vecc-mep.org.cn" target="_blank">http://www.vecc-mep.org.cn/</a>
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSVin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSVin", wsdlLocation = "http://web1.vecc-mep.org.cn/WSVin/WSVin.asmx?WSDL")
public class WSVin
    extends Service
{

    private final static URL WSVIN_WSDL_LOCATION;
    private final static WebServiceException WSVIN_EXCEPTION;
    private final static QName WSVIN_QNAME = new QName("http://web1.vecc-sepa.org.cn/WSVin", "WSVin");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://web1.vecc-mep.org.cn/WSVin/WSVin.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSVIN_WSDL_LOCATION = url;
        WSVIN_EXCEPTION = e;
    }

    public WSVin() {
        super(__getWsdlLocation(), WSVIN_QNAME);
    }

    public WSVin(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSVIN_QNAME, features);
    }

    public WSVin(URL wsdlLocation) {
        super(wsdlLocation, WSVIN_QNAME);
    }

    public WSVin(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSVIN_QNAME, features);
    }

    public WSVin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSVin(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSVinSoap
     */
    @WebEndpoint(name = "WSVinSoap")
    public WSVinSoap getWSVinSoap() {
        return super.getPort(new QName("http://web1.vecc-sepa.org.cn/WSVin", "WSVinSoap"), WSVinSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSVinSoap
     */
    @WebEndpoint(name = "WSVinSoap")
    public WSVinSoap getWSVinSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://web1.vecc-sepa.org.cn/WSVin", "WSVinSoap"), WSVinSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSVIN_EXCEPTION!= null) {
            throw WSVIN_EXCEPTION;
        }
        return WSVIN_WSDL_LOCATION;
    }

}
